//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comentario()
        {
            this.Respuestas_Comentarios = new HashSet<Respuestas_Comentarios>();
        }
    
        public int ID_comentario { get; set; }
        public Nullable<int> Documento_estudiante { get; set; }
        public Nullable<int> ID_curso { get; set; }
        public string Comentario1 { get; set; }
        public Nullable<System.DateTime> Fecha_comentario { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
        [JsonIgnore]
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Respuestas_Comentarios> Respuestas_Comentarios { get; set; }
    }
}
