//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Curso_Materias
    {
        public int ID_relacion { get; set; }
        public Nullable<int> ID_curso { get; set; }
        public Nullable<int> ID_materia { get; set; }
        [JsonIgnore]
        public virtual Curso Curso { get; set; }
        [JsonIgnore]
        public virtual Materia Materia { get; set; }
    }
}
