//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademiaDeSistemasEntities : DbContext
    {
        public AcademiaDeSistemasEntities()
            : base("name=AcademiaDeSistemasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        [JsonIgnore]
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
        [JsonIgnore]
        public virtual DbSet<Comentario> Comentarios { get; set; }
        [JsonIgnore]
        public virtual DbSet<Curso_Materias> Curso_Materias { get; set; }
        [JsonIgnore]
        public virtual DbSet<Curso> Cursos { get; set; }
        [JsonIgnore]
        public virtual DbSet<Entregas_Tareas> Entregas_Tareas { get; set; }
        [JsonIgnore]
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        [JsonIgnore]
        public virtual DbSet<Estudiantes_becados> Estudiantes_becados { get; set; }
        [JsonIgnore]
        public virtual DbSet<Foro_Curso> Foro_Curso { get; set; }
        [JsonIgnore]
        public virtual DbSet<Inscripcione> Inscripciones { get; set; }
        [JsonIgnore]
        public virtual DbSet<Materia> Materias { get; set; }
        [JsonIgnore]
        public virtual DbSet<Pago> Pagos { get; set; }
        [JsonIgnore]
        public virtual DbSet<Profesore> Profesores { get; set; }
        [JsonIgnore]
        public virtual DbSet<Respuestas_Comentarios> Respuestas_Comentarios { get; set; }
        [JsonIgnore]
        public virtual DbSet<Tarea> Tareas { get; set; }
    }
}
