//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleInscripcion
    {
        public int Codigo { get; set; }
        public Nullable<int> ID_inscripcion { get; set; }
        public Nullable<int> Documento_estudiante { get; set; }
        public Nullable<int> Documento_profesor { get; set; }
        public Nullable<int> ID_curso { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Duracion { get; set; }
        [JsonIgnore]
        public virtual Curso Curso { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
        [JsonIgnore]
        public virtual Inscripcione Inscripcione { get; set; }
        [JsonIgnore]
        public virtual Profesore Profesore { get; set; }
    }
}
