//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Entregas_Tareas
    {
        public int ID_entrega { get; set; }
        public Nullable<int> ID_tarea { get; set; }
        public Nullable<int> Documento_estudiante { get; set; }
        public string Archivo_entrega { get; set; }
        public Nullable<System.DateTime> Fecha_entrega { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
        [JsonIgnore]
        public virtual Tarea Tarea { get; set; }
    }
}
