//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscripcione()
        {
            this.Estudiantes_becados = new HashSet<Estudiantes_becados>();
            this.Pagos = new HashSet<Pago>();
        }
    
        public int ID_inscripcion { get; set; }
        public Nullable<int> Documento_estudiante { get; set; }
        public Nullable<int> ID_curso { get; set; }
        public Nullable<System.DateTime> Fecha_inscripcion { get; set; }
        [JsonIgnore]
        public virtual Curso Curso { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Estudiantes_becados> Estudiantes_becados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Pago> Pagos { get; set; }
    }
}
