//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Academia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas_Comentarios
    {
        public int ID_respuesta { get; set; }
        public Nullable<int> Documento_estudiante { get; set; }
        public Nullable<int> ID_comentario { get; set; }
        public string Respuesta { get; set; }
        public Nullable<System.DateTime> Fecha_respuesta { get; set; }

        [JsonIgnore]
        public virtual Comentario Comentario { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
    }
}
